### ISSUE TITLE
Apply to single cell transcriptomic data

### ISSUE THREAD

**Issue by ozgunbabur** [PathwayAndDataAnalysis/TF-Analysis#1]
Apply the method to the latest version of Josh's single-cell transcriptomic data. This means a set of predictions for each cell.

This can be done in a fast fashion and a slow fashion.

Fast fashion: Use the same set of genes for all cells. (Need to filter out genes with a lot of missing values)

Slow fashion: Use only the non-missing genes for each cell

**Comment by KisanThapa** [comment]
- The slow implementation for a single cell is done. The workstation is running this implementation, I will document the runtime of this implementation when it will be done
- Fast implementation is in progress.

**Comment by KisanThapa** [comment]
An optimized fast method is done. I also optimized many lines of code, the most important optimization is a calculation of actual rank sum which improves 8.75x speed to its old unvectorized method.
